### ISSUE TITLE
Broken link (img > src)

### ISSUE THREAD

**Issue by Nosferican** [blackinai/blackinai.github.io#2]
> https://www.paypalobjects.com/en_US/i/scr/pixel.gif

Is used as an `img > src` in 

https://github.com/blackinai/blackinai.github.io/blob/a0047cc0449ba97210281bd5903ce2f6176e67d6/bai/src/components/Footer/index.js#L68
and
https://github.com/blackinai/blackinai.github.io/blob/e6c36496dd6a5a581c18ef017ebc4c4b1742210e/bai/src/components/Navbar/index.js#L108

but the link is dead. It results in

<img width="792" alt="Screen Shot 2021-03-31 at 2 21 14 PM" src="https://user-images.githubusercontent.com/2529329/113192162-712e2d00-922c-11eb-9619-4d405a795759.png">

<img width="318" alt="Screen Shot 2021-03-31 at 2 21 26 PM" src="https://user-images.githubusercontent.com/2529329/113192154-6ecbd300-922c-11eb-8af7-283e712531b3.png">

A possible solution would be to create update the link / img through https://www.paypal.com/donate/buttons.

**Comment by mirianfsilva** [comment]
Thanks for reporting @Nosferican.
